### ISSUE TITLE
In React, <select> has a value attribute

### ISSUE THREAD

**Issue by nafg** [chandu0101/sri-dom-generator#1]

**Comment by chandu0101** [comment]
ok , https://github.com/chandu0101/sri-dom-generator/blob/master/src/main/scala/sri/playground/web/RawData.scala#L165 

i believe you're working on other things (input,etc) , please send a PR all together!.

btw i am planning sri -0.6 release on 22nd ,WDYT ?

**Comment by nafg** [comment]
Are you merging my fork or do you need individual PRs?

**Comment by chandu0101** [comment]
@nafg  send PR's please :)

**Comment by chandu0101** [comment]
fixed :)
